#!/bin/bash
# valid alpha numeric inputs only

alphanum_only()
{
	# validate argument: returns 0 if all upper+lower+digits; 1 otherwise
	
	# remove all unacceptable chars.
	validchars="$(echo $1 | sed -e 's/[^[:alnum:]]//g')"
	
	if [ "$validchars" = "$1" ] ; then
		return 0
	else
		return 1
	fi
}



# main script component now
/bin/echo -n "Enter input: "
read input

# input validation
if ! alphanum_only "$input" ; then
	echo "Please enter only letters and numbers." >&2
	exit 1
else
	echo "Input is valid"
fi


exit 0
